# -*- coding: utf-8 -*-
"""air quality monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUMX6q6DnPhCeRBxlA8Z24AAColOncG6
"""

from google.colab import files
files.upload()

import os

# Make kaggle directory and move the key there
os.makedirs("/root/.kaggle", exist_ok=True)
!mv kaggle.json /root/.kaggle/kaggle.json
!chmod 600 /root/.kaggle/kaggle.json

# Install kaggle library
!pip install -q kaggle

!kaggle datasets download -d anindyajana/2005-2025-kolkata-hourly-weather-dataset
!unzip -o 2005-2025-kolkata-hourly-weather-dataset.zip -d weather_dataset

import kagglehub

# Download latest version
path = kagglehub.dataset_download("anindyajana/2005-2025-kolkata-hourly-weather-dataset")

print("Path to dataset files:", path)

# Step 4: Load Data
import pandas as pd
import os

# The dataset was extracted by kagglehub to this path
# You can verify the contents of this directory using `!ls` in a new cell
extracted_path = "/root/.cache/kagglehub/datasets/anindyajana/2005-2025-kolkata-hourly-weather-dataset/versions/1"
file_name = "2005-2025_kolkata_hourly_full_dataset.csv"
file_path = os.path.join(extracted_path, file_name)


df = pd.read_csv(file_path)

# Preview the dataset
display(df.head())

# This will download the dataset and return the extracted path
dataset_path = kagglehub.dataset_download("anindyajana/2005-2025-kolkata-hourly-weather-dataset")
print("Dataset downloaded to:", dataset_path)

import pandas as pd
import os
import kagglehub

!pip install kagglehub openpyxl

# Manually verify file name (run !ls in that path if unsure)
extracted_path = dataset_path
file_name = "Kolkata_weather_data_2005_2025.xlsx"
file_path = os.path.join(extracted_path, file_name)

# Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Load Dataset
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")

# Step 3: Select Relevant Columns
filtered_df = df[['temperature_2m', 'relative_humidity_2m', 'weather_code']].dropna()

# Optional: Map weather_code to categories for visualization
def map_aqi_category(code):
    if code <= 2:
        return 'Good'
    elif code <= 5:
        return 'Moderate'
    else:
        return 'Poor'

filtered_df['AQI_Category'] = filtered_df['weather_code'].apply(map_aqi_category)

# Step 4: Pairplot Visualization
# Rename columns for better display
plot_df = filtered_df.rename(columns={
    'temperature_2m': 'Temperature',
    'relative_humidity_2m': 'Humidity'
})

sns.pairplot(plot_df, vars=['Temperature', 'Humidity'], hue='AQI_Category', palette="Set2")
plt.suptitle("Pairplot of Temperature, Humidity and AQI Category", y=1.02)
plt.tight_layout()
plt.show()

# Step 5: ML - Features and Target
X = filtered_df[['temperature_2m', 'relative_humidity_2m']]
y = filtered_df['weather_code']

# Step 6: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Normalize Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 8: Train ML Model
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)

# Step 9: Predictions
y_pred = clf.predict(X_test_scaled)

# Step 10: Evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 11: Feature Importance Plot
importances = clf.feature_importances_
feat_labels = ['temperature_2m', 'relative_humidity_2m']

plt.figure(figsize=(6, 4))
sns.barplot(x=importances, y=feat_labels)
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.grid(True)
plt.tight_layout()
plt.show()

# Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Load the Dataset
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")  # Change path if needed

# Step 3: Drop rows with missing values
df = df.dropna()

# Step 4: Encode target if it's categorical
if df['weather_code'].dtype == 'object':
    df['weather_code'] = df['weather_code'].astype('category').cat.codes

# Step 5: Features and Target
X = df.drop(columns=['weather_code', 'time'])  # Drop target and timestamp
y = df['weather_code']

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 8: Train Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)

# Step 9: Predict and Evaluate
y_pred = clf.predict(X_test_scaled)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 10: Feature Importance Plot
importances = clf.feature_importances_
feat_labels = X.columns

plt.figure(figsize=(10, 6))
sns.barplot(x=importances, y=feat_labels)
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.tight_layout()
plt.grid()
plt.show()

# Step 11: Pairplot for key features
sns.pairplot(df[['temperature_2m', 'relative_humidity_2m', 'surface_pressure', 'wind_speed_10m', 'weather_code']],
             hue='weather_code', palette='Set2')
plt.show()

# Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Load the Dataset
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")

# Step 3: Features & Target
X = df[['temperature_2m', 'relative_humidity_2m']]
y = df['weather_code']

# Step 4: Split into Train and Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Normalize Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 6: Train ML Model (Random Forest Classifier)
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)

# Step 7: Predict
y_pred = clf.predict(X_test_scaled)

# Step 8: Evaluate
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 9: Feature Importance Plot
importances = clf.feature_importances_
feat_labels = ['temperature_2m', 'relative_humidity_2m']

plt.figure(figsize=(6, 4))
sns.barplot(x=importances, y=feat_labels)
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.grid(True)
plt.tight_layout()
plt.show()

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Load the Dataset
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")

print("Dataset Shape:", df.shape)
print("Columns:", df.columns.tolist())

# Step 3: Prepare Feature Matrix and Target
# Drop 'date' and rows with missing target
df = df.dropna(subset=['weather_code'])
X = df.drop(columns=['date', 'weather_code'])
y = df['weather_code']

# Optional: Fill missing values in features
X = X.fillna(X.mean())

# Step 4: Split into Train and Test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 5: Normalize Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 6: Train Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)

# Step 7: Predict
y_pred = clf.predict(X_test_scaled)

# Step 8: Evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 9: Feature Importance Plot
importances = clf.feature_importances_
feat_labels = X.columns

plt.figure(figsize=(10, 8))
sns.barplot(x=importances, y=feat_labels, palette="viridis")
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.tight_layout()
plt.show()

# Accuracy
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

# Pairplot (selected features)
plot_df = X.copy()
plot_df['weather_code'] = y
sns.pairplot(plot_df[['temperature_2m', 'relative_humidity_2m', 'pressure_msl', 'wind_speed_10m', 'weather_code']],
             hue="weather_code", palette="Set2")
plt.suptitle("Pairplot of Selected Features and Weather Code", y=1.02)
plt.show()

# Heatmap
plt.figure(figsize=(14, 12))
sns.heatmap(X.corr(), cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

plt.figure(figsize=(16, 14))
corr = X.corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Feature Correlation Heatmap with Values")
plt.show()

from sklearn.metrics import accuracy_score

# y_test: true labels
# y_pred: predicted labels
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



# 📌 Core
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 📌 Scikit-learn
from sklearn.model_selection import train_test_split, validation_curve
from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score, roc_curve, auc

# 📌 Gradient Boosting Models
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# ============================================
# ✅ 1) Install Libraries (Colab)
# ============================================
!pip install xgboost lightgbm

# ============================================
# ✅ 2) Import Libraries
# ============================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, validation_curve
from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score, roc_curve, auc

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# ============================================
# ✅ 3) Load Data
# ============================================
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

# ============================================
# ✅ 4) Prepare Data
# ============================================
df = df.dropna(subset=['weather_code'])

X = df.drop(columns=['date', 'weather_code'])
X = X.fillna(X.mean())
y = df['weather_code']

# Encode target labels for XGBoost
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Binarize for multi-class ROC AUC
classes = np.unique(y_train)
y_test_bin = label_binarize(y_test, classes=classes)
n_classes = y_test_bin.shape[1]

# ============================================
# ✅ 5) Define 4 Models (No CatBoost)
# ============================================
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'AdaBoost': AdaBoostClassifier(n_estimators=100, random_state=42),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'),
    'LightGBM': LGBMClassifier()
}

results = {}

# ============================================
# ✅ 6) Train & Evaluate
# ============================================
for name, model in models.items():
    print(f"\n=== Training {name} ===")
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    y_proba = model.predict_proba(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    logloss = log_loss(y_test, y_proba)
    rocauc = roc_auc_score(y_test_bin, y_proba, multi_class='ovr')

    print(f"Accuracy: {acc:.4f}")
    print(f"Log Loss: {logloss:.4f}")
    print(f"ROC AUC: {rocauc:.4f}")

    results[name] = {
        'Accuracy': acc,
        'LogLoss': logloss,
        'ROC_AUC': rocauc,
        'Proba': y_proba
    }

# ============================================
# ✅ 7) Accuracy Bar Chart (4 Models)
# ============================================
accuracies = {name: res['Accuracy'] for name, res in results.items()}

acc_df = pd.DataFrame.from_dict(accuracies, orient='index', columns=['Accuracy'])

acc_df.plot(kind='bar', figsize=(10, 6), color='skyblue', legend=False)
plt.title('Accuracy Comparison (Random Forest, AdaBoost, XGBoost, LightGBM)')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Get Log Loss values
loglosses = {name: res['LogLoss'] for name, res in results.items()}

# To DataFrame
logloss_df = pd.DataFrame.from_dict(loglosses, orient='index', columns=['LogLoss'])

# Plot
logloss_df.plot(kind='bar', figsize=(10, 6), color='salmon', legend=False)
plt.title('Log Loss Comparison (Random Forest, AdaBoost, XGBoost, LightGBM)')
plt.ylabel('Log Loss')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

# Step 2: Load Dataset
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")  # Update path if needed

# Step 3: Drop missing values
df.dropna(inplace=True)

# Step 4: Encode target
if df['weather_code'].dtype == 'object':
    df['weather_code'] = df['weather_code'].astype('category').cat.codes

# Step 5: Features and Target
X = df.drop(columns=['weather_code', 'date'])
y = df['weather_code']

# Step 6: Binarize target for ROC curve
lb = LabelBinarizer()
y_bin = lb.fit_transform(y)

# Step 7: Split dataset
X_train, X_test, y_train_bin, y_test_bin = train_test_split(X, y_bin, test_size=0.2, random_state=42)

# Step 8: Normalize Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 9: Train One-vs-Rest Random Forest
clf = OneVsRestClassifier(RandomForestClassifier(n_estimators=100, random_state=42))
clf.fit(X_train_scaled, y_train_bin)

# Step 10: Predict probabilities
y_score = clf.predict_proba(X_test_scaled)

# Step 11: ROC Curve and AUC for Each Class
fpr = dict()
tpr = dict()
roc_auc = dict()
n_classes = y_bin.shape[1]

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Step 12: Plot All ROC Curves
plt.figure(figsize=(10, 7))
colors = plt.cm.tab10.colors

for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], color=colors[i % 10],
             label='Class {} (AUC = {:.2f})'.format(i, roc_auc[i]))

plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Multi-Class ROC Curve')
plt.legend(loc='lower right')
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(10, 8))

for name, model in models.items():
    y_proba = model.predict_proba(X_test_scaled)
    fpr, tpr, _ = roc_curve(y_test_bin[:, 0], y_proba[:, 0])  # Class 0 as example
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--', label="Random Classifier")
plt.title("ROC Curve Comparison (Class 0)")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid(True)
plt.show()

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Load the Dataset
df = pd.read_csv("/2005-2025_kolkata_hourly_full_dataset.csv")

# Optional: Display basic info
print("Dataset Shape:", df.shape)
print("Columns:", df.columns.tolist())

# Step 3: Select Relevant Features
filtered_df = df[['temperature_2m', 'relative_humidity_2m', 'weather_code']].dropna()

# Step 4: Pairplot for Visualization
# Rename columns for readability in plot
plot_df = filtered_df.rename(columns={
    'temperature_2m': 'Temperature',
    'relative_humidity_2m': 'Humidity',
    'weather_code': 'AQI_Code'
})

# Optional: Map AQI code to category (update this logic based on real meaning if known)
def map_aqi_category(code):
    if code <= 2:
        return 'Good'
    elif code <= 5:
        return 'Moderate'
    else:
        return 'Poor'

plot_df['AQI_Category'] = plot_df['AQI_Code'].apply(map_aqi_category)

# Plot pairplot
sns.pairplot(plot_df, hue="AQI_Category", palette="Set2")
plt.suptitle("Pairplot of Weather Parameters and AQI Category", y=1.02)
plt.show()

# Step 5: ML Feature Matrix and Target Vector
X = filtered_df[['temperature_2m', 'relative_humidity_2m']]
y = filtered_df['weather_code']

# Step 6: Split into Train and Test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 7: Normalize Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 8: Train Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)

# Step 9: Predict
y_pred = clf.predict(X_test_scaled)

# Step 10: Evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 11: Feature Importance Plot
importances = clf.feature_importances_
feat_labels = ['temperature_2m', 'relative_humidity_2m']

plt.figure(figsize=(6, 4))
sns.barplot(x=importances, y=feat_labels, palette="viridis")
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.grid(True)
plt.tight_layout()
plt.show()

from google.colab import files
files.download("kolkata_weather_subset_100.csv")