# -*- coding: utf-8 -*-
"""Another copy of ieee project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3hZ4AF6hKLlIg4F-yU7K-RmAlnHG0d-
"""

!pip install numpy pandas scikit-learn seaborn matplotlib lightgbm catboost pytorch-tabnet shap statsmodels openpyxl
# Imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import StackingClassifier, RandomForestClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.calibration import calibration_curve
from statsmodels.stats.contingency_tables import mcnemar
import shap
import time
import warnings
warnings.filterwarnings("ignore")

# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00342/Data_Cortex_Nuclear.xls"
data = pd.read_excel(url)

# Drop missing values
data.dropna(inplace=True)

# Features and labels
X = data.drop(columns=['MouseID', 'Genotype', 'Treatment', 'Behavior', 'class'])
y = data['class']

# Normalize
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Feature selection
rf = RandomForestClassifier(random_state=42)
rf.fit(X_scaled, y)
top_idx = np.argsort(rf.feature_importances_)[-10:]
X_selected = X_scaled[:, top_idx]
feature_names = X.columns[top_idx]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, stratify=y, random_state=42)

# Base and stacking model
base_models = [
    ("tabnet", TabNetClassifier(verbose=0, seed=42)),
    ("catboost", CatBoostClassifier(verbose=0, random_seed=42))
]
stacking_model = StackingClassifier(
    estimators=base_models,
    final_estimator=LGBMClassifier(random_state=42),
    n_jobs=-1
)

# Fit
stacking_model.fit(X_train, y_train)

# Predict
pred = stacking_model.predict(X_test)
probs = stacking_model.predict_proba(X_test)

# Accuracy & report
print(f"\nAccuracy: {accuracy_score(y_test, pred):.4f}")
print("\nClassification Report:\n", classification_report(y_test, pred))

# Confusion matrix
sns.heatmap(confusion_matrix(y_test, pred), annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# SHAP explanation
explainer = shap.Explainer(stacking_model.final_estimator_, X_train)
shap_vals = explainer(X_test)
shap.summary_plot(shap_vals, X_test, feature_names=feature_names)

# Import necessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA
from sklearn.calibration import CalibratedClassifierCV
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Load dataset (correct URL and format for UCI Ionosphere dataset)
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
column_names = [f"Feature_{i}" for i in range(1, 35)] + ['status']  # Adding custom column names
data_frame = pd.read_csv(data_url, header=None, names=column_names)

# Data Preprocessing: Split the data into features (X) and target (Y)
X = data_frame.drop(columns=['status'])
Y = data_frame['status'].map({'g': 1, 'b': 0})  # Mapping 'g' to 1 and 'b' to 0

# Normalize features using MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2, stratify=Y)

# Apply PCA for dimensionality reduction
pca = PCA(n_components=10)  # Reduce to 10 components for better performance in some models
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

# Define the base models for stacking
base_models = [
    ('rf', RandomForestClassifier(n_estimators=100)),
    ('gb', GradientBoostingClassifier(n_estimators=100)),
    ('xgb', XGBClassifier(use_label_encoder=False, eval_metric='logloss')),
    ('lgbm', LGBMClassifier()),
    ('catboost', CatBoostClassifier(verbose=0)),
    ('tabnet', TabNetClassifier())
]

# Create the stacking model
stacking_model = StackingClassifier(
    estimators=base_models,
    final_estimator=RandomForestClassifier(n_estimators=100)
)

# Fit the stacking model using the training data (original features, before PCA)
stacking_model.fit(X_train, Y_train)

# Calibrate the stacking model for better probability estimates
calibrated_stacking_model = CalibratedClassifierCV(stacking_model, method='sigmoid', cv='prefit')
calibrated_stacking_model.fit(X_train, Y_train)  # Fit calibration on original data

# Evaluate the calibrated model using PCA-transformed test data
predictions = calibrated_stacking_model.predict(X_test_pca)
accuracy = accuracy_score(Y_test, predictions)

# Print evaluation results
print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
cm = confusion_matrix(Y_test, predictions)
print(cm)
print("Classification Report:")
print(classification_report(Y_test, predictions))

# Visualize the confusion matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Calibrated Stacking Model')
plt.show()

# Accuracy Comparison Plot for all models
models = {
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
    "LightGBM": LGBMClassifier(),
    "CatBoost": CatBoostClassifier(verbose=0),
    "TabNet": TabNetClassifier()
}

accuracies = {}
for model_name, model in models.items():
    model.fit(X_train, Y_train)
    pred = model.predict(X_test)
    accuracies[model_name] = accuracy_score(Y_test, pred)

# Plot accuracy comparison
plt.figure(figsize=(12, 6))
plt.barh(list(accuracies.keys()), list(accuracies.values()), color='skyblue')
plt.xlabel('Accuracy')
plt.ylabel('Models')
plt.title('Accuracy Comparison of All Models')
plt.show()

# Feature Correlation Heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(pd.DataFrame(X, columns=data_frame.columns[:-1]).corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()

!pip install optuna

# Import necessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, validation_curve
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier, StackingClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report

# Load dataset
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
column_names = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data_frame = pd.read_csv(data_url, header=None, names=column_names)

# Data Preprocessing
X = data_frame.drop(columns=['status'])
Y = data_frame['status'].map({'g': 1, 'b': 0})
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2, stratify=Y)

# Define base models
base_models = {
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100),
    "AdaBoost": AdaBoostClassifier(n_estimators=100),
    "Extra Trees": ExtraTreesClassifier(n_estimators=100),
    "LightGBM": LGBMClassifier(),
    "CatBoost": CatBoostClassifier(verbose=0),
    "TabNet": TabNetClassifier()
}

# Stacking Ensemble
estimators = [(name, model) for name, model in base_models.items()]
stack_model = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(), cv=5)
base_models["Stacking Ensemble"] = stack_model

# Validation curve plotting
param_ranges = {
    "Gradient Boosting": ("n_estimators", np.arange(10, 200, 20)),
    "AdaBoost": ("n_estimators", np.arange(10, 200, 20)),
    "Extra Trees": ("n_estimators", np.arange(10, 200, 20)),
    "LightGBM": ("n_estimators", np.arange(10, 200, 20)),
    "CatBoost": ("depth", np.arange(3, 10)),
    "TabNet": ("n_d", np.arange(8, 32, 4))
    # No validation curve for stacking
}

def plot_validation_curve(model, param_name, param_range, X_train, Y_train):
    train_scores, test_scores = validation_curve(model, X_train, Y_train, param_name=param_name, param_range=param_range, cv=5, scoring='accuracy')
    plt.figure(figsize=(10, 6))
    plt.plot(param_range, np.mean(train_scores, axis=1), label='Training Score', marker='o')
    plt.plot(param_range, np.mean(test_scores, axis=1), label='Validation Score', marker='s')
    plt.xlabel(param_name)
    plt.ylabel('Accuracy')
    plt.title(f'Validation Curve for {model.__class__.__name__}')
    plt.legend()
    plt.show()

for name, (param, values) in param_ranges.items():
    plot_validation_curve(base_models[name], param, values, X_train, Y_train)

# Evaluate models
test_accuracies = {}
loss_scores = {}

for name, model in base_models.items():
    try:
        model.fit(X_train, Y_train)
        predictions = model.predict(X_test)
        test_accuracies[name] = accuracy_score(Y_test, predictions)

        print(f"\nModel: {name}")
        print(f"Accuracy: {test_accuracies[name]:.4f}")
        cm = confusion_matrix(Y_test, predictions)
        print("Confusion Matrix:")
        print(cm)
        print("Classification Report:")
        print(classification_report(Y_test, predictions))

        # Confusion matrix heatmap
        plt.figure(figsize=(6, 5))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'Confusion Matrix - {name}')
        plt.show()

        # Log loss
        if hasattr(model, 'predict_proba'):
            loss_scores[name] = log_loss(Y_test, model.predict_proba(X_test)[:, 1])

    except Exception as e:
        print(f"Error in model {name}: {e}")

# Accuracy comparison plot
plt.figure(figsize=(12, 6))
plt.barh(list(test_accuracies.keys()), list(test_accuracies.values()), color='skyblue')
plt.xlabel('Accuracy')
plt.ylabel('Models')
plt.title('Accuracy Comparison of All Models')
plt.show()

# Log loss plot
plt.figure(figsize=(10, 6))
plt.plot(loss_scores.keys(), loss_scores.values(), marker='o', linestyle='-', color='red', markersize=8)
plt.xlabel('Models')
plt.ylabel('Cross Entropy Loss')
plt.title('Binary vs Categorical Cross Entropy Loss')
plt.xticks(rotation=45)
plt.show()

# Feature correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(pd.DataFrame(X, columns=data_frame.columns[:-1]).corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()

# Optional: Pairplot visualization (may be slow for 34 features)
# pairplot_data = pd.DataFrame(X, columns=data_frame.columns[:-1])
# sns.pairplot(pairplot_data.iloc[:, :6], diag_kind='kde')  # Plot only first few features to keep it readable
# plt.show()

# Enhanced Ionosphere Classification with Explainability, Optimization & Deployment

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
!pip install optuna

import optuna

# Load dataset
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
column_names = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(data_url, header=None, names=column_names)
data['status'] = data['status'].map({'g': 1, 'b': 0})
X = data.drop(columns=['status'])
Y = data['status']
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Optuna tuning for LightGBM
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15)
    }
    model = LGBMClassifier(**params)
    model.fit(X_train, Y_train)
    pred = model.predict(X_test)
    return 1.0 - accuracy_score(Y_test, pred)

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)
optuna_best = LGBMClassifier(**study.best_params)
optuna_best.fit(X_train, Y_train)

# Define other models
models = {
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100),
    "AdaBoost": AdaBoostClassifier(n_estimators=100),
    "Extra Trees": ExtraTreesClassifier(n_estimators=100),
    "LightGBM (Optuna Tuned)": optuna_best,
    "CatBoost": CatBoostClassifier(verbose=0, iterations=100),
    "TabNet": TabNetClassifier(verbose=0)
}

# Stacking ensemble
estimators = [(name, model) for name, model in models.items()]
stack = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(), cv=5)
models["Stacking Ensemble"] = stack

# Evaluation
results = {}
for name, model in models.items():
    try:
        model.fit(X_train, Y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(Y_test, preds)
        results[name] = acc
        print(f"\n{name} Accuracy: {acc:.4f}")
        print(confusion_matrix(Y_test, preds))
        print(classification_report(Y_test, preds))

        # Permutation Importance
        if name != "Stacking Ensemble":
            r = permutation_importance(model, X_test, Y_test, n_repeats=10, random_state=0)
            top_idx = r.importances_mean.argsort()[::-1][:5]
            print(f"Top Features for {name}: {[column_names[i] for i in top_idx]}")

        # SHAP Explainability
        if name in ["LightGBM (Optuna Tuned)", "CatBoost"]:
            explainer = shap.Explainer(model)
            shap_values = explainer(X_test)
            shap.summary_plot(shap_values, X_test, feature_names=column_names[:-1], show=False)
            plt.title(f"SHAP Summary for {name}")
            plt.tight_layout()
            plt.savefig(f"shap_{name}.png")
            plt.close()

    except Exception as e:
        print(f"Error in {name}: {e}")

# Accuracy comparison
plt.figure(figsize=(10, 6))
plt.barh(list(results.keys()), list(results.values()), color='skyblue')
plt.xlabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.tight_layout()
plt.savefig("accuracy_comparison.png")

# Save best model
best_model_name = max(results, key=results.get)
joblib.dump(models[best_model_name], "best_model.pkl")
print(f"\nBest model '{best_model_name}' saved as 'best_model.pkl'")

# Enhanced Ionosphere Classification with Explainability, Optimization & Deployment

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
import optuna

# Load dataset
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
column_names = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(data_url, header=None, names=column_names)
data['status'] = data['status'].map({'g': 1, 'b': 0})
X = data.drop(columns=['status'])
Y = data['status']
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Optuna tuning for LightGBM
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15)
    }
    model = LGBMClassifier(**params)
    model.fit(X_train, Y_train)
    pred = model.predict(X_test)
    return 1.0 - accuracy_score(Y_test, pred)

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)
optuna_best = LGBMClassifier(**study.best_params)
optuna_best.fit(X_train, Y_train)

# Define other models
models = {
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100),
    "AdaBoost": AdaBoostClassifier(n_estimators=100),
    "Extra Trees": ExtraTreesClassifier(n_estimators=100),
    "LightGBM (Optuna Tuned)": optuna_best,
    "CatBoost": CatBoostClassifier(verbose=0, iterations=100),
    "TabNet": TabNetClassifier(verbose=0)
}

# Stacking ensemble
estimators = [(name, model) for name, model in models.items()]
stack = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(), cv=5)
models["Stacking Ensemble"] = stack

# Evaluation
results = {}
for name, model in models.items():
    try:
        model.fit(X_train, Y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(Y_test, preds)
        results[name] = acc
        print(f"\n{name} Accuracy: {acc:.4f}")
        print(confusion_matrix(Y_test, preds))
        print(classification_report(Y_test, preds))

        # Permutation Importance
        if name != "Stacking Ensemble":
            r = permutation_importance(model, X_test, Y_test, n_repeats=10, random_state=0)
            top_idx = r.importances_mean.argsort()[::-1][:5]
            print(f"Top Features for {name}: {[column_names[i] for i in top_idx]}")

        # SHAP Explainability
        if name in ["LightGBM (Optuna Tuned)", "CatBoost"]:
            explainer = shap.Explainer(model)
            shap_values = explainer(X_test)
            shap.summary_plot(shap_values, X_test, feature_names=column_names[:-1], show=False)
            plt.title(f"SHAP Summary for {name}")
            plt.tight_layout()
            plt.savefig(f"shap_{name}.png")
            plt.close()

    except Exception as e:
        print(f"Error in {name}: {e}")

# Accuracy comparison
plt.figure(figsize=(10, 6))
plt.barh(list(results.keys()), list(results.values()), color='skyblue')
plt.xlabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.tight_layout()
plt.savefig("accuracy_comparison.png")

# Save best model
best_model_name = max(results, key=results.get)
joblib.dump(models[best_model_name], "best_model.pkl")
print(f"\nBest model '{best_model_name}' saved as 'best_model.pkl'")

# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import StackingClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, log_loss
from sklearn.inspection import permutation_importance
from sklearn.calibration import calibration_curve
from statsmodels.stats.contingency_tables import mcnemar
import shap
import time
import warnings
warnings.filterwarnings("ignore")

# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
columns = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(url, header=None, names=columns)
X = data.drop('status', axis=1)
y = data['status'].map({'g': 1, 'b': 0})

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Feature Selection with LGBM
def select_top_features(model, X, y, feature_names, num_features=10):
    model.fit(X, y)
    importance = model.feature_importances_
    top_idx = np.argsort(importance)[-num_features:]
    return top_idx, feature_names[top_idx]

feature_names = np.array(X.columns)
top_idx, selected_features = select_top_features(LGBMClassifier(), X_scaled, y, feature_names)
X_selected = X_scaled[:, top_idx]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, stratify=y, random_state=42)

# Base models
base_models = [
    ("tabnet", TabNetClassifier(verbose=0)),
    ("cat", CatBoostClassifier(verbose=0))
]

# Stacking classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=LGBMClassifier())
stacking_model.fit(X_train, y_train)
pred = stacking_model.predict(X_test)
probs = stacking_model.predict_proba(X_test)[:, 1]

# Accuracy
acc = accuracy_score(y_test, pred)
print(f"Stacking Model Accuracy: {acc:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Classification Report
print("\nClassification Report:\n", classification_report(y_test, pred))

# Permutation Importance
perm = permutation_importance(stacking_model, X_test, y_test, n_repeats=5)
importances_df = pd.DataFrame({"Feature": selected_features, "Importance": perm.importances_mean})
print("\nTop Permutation Importances:\n", importances_df.sort_values(by='Importance', ascending=False).head())

# SHAP Analysis
explainer = shap.Explainer(stacking_model.final_estimator_, X_train)
shap_vals = explainer(X_test)
shap.summary_plot(shap_vals, X_test, feature_names=selected_features)

# Calibration Curve
prob_true, prob_pred = calibration_curve(y_test, probs, n_bins=10)
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('Mean Predicted Probability')
plt.ylabel('True Probability')
plt.title('Calibration Curve')
plt.show()

# Time Complexity Profiling
start_time = time.time()
_ = stacking_model.predict(X_test)
end_time = time.time()
print(f"Prediction time: {end_time - start_time:.4f} seconds")

# Bootstrap Test
def bootstrap_test(y_true, y_pred1, y_pred2, n_iter=1000):
    y_true, y_pred1, y_pred2 = np.array(y_true), np.array(y_pred1), np.array(y_pred2)
    diff = np.mean(y_pred1 == y_true) - np.mean(y_pred2 == y_true)
    diffs = []
    for _ in range(n_iter):
        idx = np.random.choice(len(y_true), len(y_true), replace=True)
        d = np.mean(y_pred1[idx] == y_true[idx]) - np.mean(y_pred2[idx] == y_true[idx])
        diffs.append(d)
    p_val = np.mean(np.abs(diffs) >= np.abs(diff))
    return p_val

cat_model = CatBoostClassifier(verbose=0)
cat_model.fit(X_train, y_train)
cat_pred = cat_model.predict(X_test)
p_value = bootstrap_test(y_test, cat_pred, pred)
print(f"Bootstrap Test p-value: {p_value:.4f}")

# McNemar Test
mcnemar_table = confusion_matrix(cat_pred, pred)
mcnemar_result = mcnemar(mcnemar_table, exact=True)
print(f"McNemar's Test p-value: {mcnemar_result.pvalue:.4f}")

# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, log_loss
from sklearn.inspection import permutation_importance
from sklearn.calibration import calibration_curve
from statsmodels.stats.contingency_tables import mcnemar
import shap
import time
import joblib
import optuna
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier

# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
columns = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(url, header=None, names=columns)
data['status'] = data['status'].map({'g': 1, 'b': 0})
X = data.drop('status', axis=1)
y = data['status']

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Feature Selection with LGBM
def select_top_features(model, X, y, feature_names, num_features=10):
    model.fit(X, y)
    importance = model.feature_importances_
    top_idx = np.argsort(importance)[-num_features:]
    return top_idx, feature_names[top_idx]

feature_names = np.array(X.columns)
top_idx, selected_features = select_top_features(LGBMClassifier(), X_scaled, y, feature_names)
X_selected = X_scaled[:, top_idx]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, stratify=y, random_state=42)

# Hyperparameter Tuning with Optuna for LightGBM
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15)
    }
    model = LGBMClassifier(**params)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    return 1.0 - accuracy_score(y_test, pred)

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)
optuna_best = LGBMClassifier(**study.best_params)
optuna_best.fit(X_train, y_train)

# Base models
base_models = [
    ("tabnet", TabNetClassifier(verbose=0)),
    ("cat", CatBoostClassifier(verbose=0))
]

# Stacking classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=optuna_best)
stacking_model.fit(X_train, y_train)
pred = stacking_model.predict(X_test)
probs = stacking_model.predict_proba(X_test)[:, 1]

# Accuracy
acc = accuracy_score(y_test, pred)
print(f"Stacking Model Accuracy: {acc:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Classification Report
print("\nClassification Report:\n", classification_report(y_test, pred))

# Permutation Importance
perm = permutation_importance(stacking_model, X_test, y_test, n_repeats=5)
importances_df = pd.DataFrame({"Feature": selected_features, "Importance": perm.importances_mean})
print("\nTop Permutation Importances:\n", importances_df.sort_values(by='Importance', ascending=False).head())

# SHAP Analysis
explainer = shap.Explainer(stacking_model.final_estimator_, X_train)
shap_vals = explainer(X_test)
shap.summary_plot(shap_vals, X_test, feature_names=selected_features)

# Calibration Curve
prob_true, prob_pred = calibration_curve(y_test, probs, n_bins=10)
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('Mean Predicted Probability')
plt.ylabel('True Probability')
plt.title('Calibration Curve')
plt.show()

# Time Complexity Profiling
start_time = time.time()
_ = stacking_model.predict(X_test)
end_time = time.time()
print(f"Prediction time: {end_time - start_time:.4f} seconds")

# Bootstrap Test
def bootstrap_test(y_true, y_pred1, y_pred2, n_iter=1000):
    y_true, y_pred1, y_pred2 = np.array(y_true), np.array(y_pred1), np.array(y_pred2)
    diff = np.mean(y_pred1 == y_true) - np.mean(y_pred2 == y_true)
    diffs = []
    for _ in range(n_iter):
        idx = np.random.choice(len(y_true), len(y_true), replace=True)
        d = np.mean(y_pred1[idx] == y_true[idx]) - np.mean(y_pred2[idx] == y_true[idx])
        diffs.append(d)
    p_val = np.mean(np.abs(diffs) >= np.abs(diff))
    return p_val

cat_model = CatBoostClassifier(verbose=0)
cat_model.fit(X_train, y_train)
cat_pred = cat_model.predict(X_test)
p_value = bootstrap_test(y_test, cat_pred, pred)
print(f"Bootstrap Test p-value: {p_value:.4f}")

# McNemar Test
mcnemar_table = confusion_matrix(cat_pred, pred)
mcnemar_result = mcnemar(mcnemar_table, exact=True)
print(f"McNemar's Test p-value: {mcnemar_result.pvalue:.4f}")

# Save best model
joblib.dump(stacking_model, "best_model.pkl")
print("Best model saved as 'best_model.pkl'")

# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, log_loss
from sklearn.inspection import permutation_importance
from sklearn.calibration import calibration_curve
from statsmodels.stats.contingency_tables import mcnemar
import shap
import time
import joblib
import optuna
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier

# Load dataset
url = "# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, log_loss
from sklearn.inspection import permutation_importance
from sklearn.calibration import calibration_curve
from statsmodels.stats.contingency_tables import mcnemar
import shap
import time
import joblib
import optuna
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier

# Load dataset
url = "https://archive.ics.uci.edu/ml/datasets/Molecular+Biology+%28Splice-junction+Gene+Sequences%29"
columns = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(url, header=None, names=columns)
data['status'] = data['status'].map({'g': 1, 'b': 0})
X = data.drop('status', axis=1)
y = data['status']

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Feature Selection with LGBM
def select_top_features(model, X, y, feature_names, num_features=10):
    model.fit(X, y)
    importance = model.feature_importances_
    top_idx = np.argsort(importance)[-num_features:]
    return top_idx, feature_names[top_idx]

feature_names = np.array(X.columns)
top_idx, selected_features = select_top_features(LGBMClassifier(), X_scaled, y, feature_names)
X_selected = X_scaled[:, top_idx]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, stratify=y, random_state=42)

# Hyperparameter Tuning with Optuna for LightGBM
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15)
    }
    model = LGBMClassifier(**params)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    return 1.0 - accuracy_score(y_test, pred)

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)
optuna_best = LGBMClassifier(**study.best_params)
optuna_best.fit(X_train, y_train)

# Base models
base_models = [
    ("tabnet", TabNetClassifier(verbose=0)),
    ("cat", CatBoostClassifier(verbose=0))
]

# Stacking classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=optuna_best)
stacking_model.fit(X_train, y_train)
pred = stacking_model.predict(X_test)
probs = stacking_model.predict_proba(X_test)[:, 1]

# Accuracy
acc = accuracy_score(y_test, pred)
print(f"Stacking Model Accuracy: {acc:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Classification Report
print("\nClassification Report:\n", classification_report(y_test, pred))

# Permutation Importance
perm = permutation_importance(stacking_model, X_test, y_test, n_repeats=5)
importances_df = pd.DataFrame({"Feature": selected_features, "Importance": perm.importances_mean})
print("\nTop Permutation Importances:\n", importances_df.sort_values(by='Importance', ascending=False).head())

# SHAP Analysis
explainer = shap.Explainer(stacking_model.final_estimator_, X_train)
shap_vals = explainer(X_test)
shap.summary_plot(shap_vals, X_test, feature_names=selected_features)

# Calibration Curve
prob_true, prob_pred = calibration_curve(y_test, probs, n_bins=10)
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('Mean Predicted Probability')
plt.ylabel('True Probability')
plt.title('Calibration Curve')
plt.show()

# Time Complexity Profiling
start_time = time.time()
_ = stacking_model.predict(X_test)
end_time = time.time()
print(f"Prediction time: {end_time - start_time:.4f} seconds")

# Bootstrap Test
def bootstrap_test(y_true, y_pred1, y_pred2, n_iter=1000):
    y_true, y_pred1, y_pred2 = np.array(y_true), np.array(y_pred1), np.array(y_pred2)
    diff = np.mean(y_pred1 == y_true) - np.mean(y_pred2 == y_true)
    diffs = []
    for _ in range(n_iter):
        idx = np.random.choice(len(y_true), len(y_true), replace=True)
        d = np.mean(y_pred1[idx] == y_true[idx]) - np.mean(y_pred2[idx] == y_true[idx])
        diffs.append(d)
    p_val = np.mean(np.abs(diffs) >= np.abs(diff))
    return p_val

cat_model = CatBoostClassifier(verbose=0)
cat_model.fit(X_train, y_train)
cat_pred = cat_model.predict(X_test)
p_value = bootstrap_test(y_test, cat_pred, pred)
print(f"Bootstrap Test p-value: {p_value:.4f}")

# McNemar Test
mcnemar_table = confusion_matrix(cat_pred, pred)
mcnemar_result = mcnemar(mcnemar_table, exact=True)
print(f"McNemar's Test p-value: {mcnemar_result.pvalue:.4f}")

# Save best model
joblib.dump(stacking_model, "best_model.pkl")
print("Best model saved as 'best_model.pkl'")
"
columns = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(url, header=None, names=columns)
data['status'] = data['status'].map({'g': 1, 'b': 0})
X = data.drop('status', axis=1)
y = data['status']

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Feature Selection with LGBM
def select_top_features(model, X, y, feature_names, num_features=10):
    model.fit(X, y)
    importance = model.feature_importances_
    top_idx = np.argsort(importance)[-num_features:]
    return top_idx, feature_names[top_idx]

feature_names = np.array(X.columns)
top_idx, selected_features = select_top_features(LGBMClassifier(), X_scaled, y, feature_names)
X_selected = X_scaled[:, top_idx]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, stratify=y, random_state=42)

# Hyperparameter Tuning with Optuna for LightGBM
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15)
    }
    model = LGBMClassifier(**params)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    return 1.0 - accuracy_score(y_test, pred)

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)
optuna_best = LGBMClassifier(**study.best_params)
optuna_best.fit(X_train, y_train)

# Base models
base_models = [
    ("tabnet", TabNetClassifier(verbose=0)),
    ("cat", CatBoostClassifier(verbose=0))
]

# Stacking classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=optuna_best)
stacking_model.fit(X_train, y_train)
pred = stacking_model.predict(X_test)
probs = stacking_model.predict_proba(X_test)[:, 1]

# Accuracy
acc = accuracy_score(y_test, pred)
print(f"Stacking Model Accuracy: {acc:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Classification Report
print("\nClassification Report:\n", classification_report(y_test, pred))

# Permutation Importance
perm = permutation_importance(stacking_model, X_test, y_test, n_repeats=5)
importances_df = pd.DataFrame({"Feature": selected_features, "Importance": perm.importances_mean})
print("\nTop Permutation Importances:\n", importances_df.sort_values(by='Importance', ascending=False).head())

# SHAP Analysis
explainer = shap.Explainer(stacking_model.final_estimator_, X_train)
shap_vals = explainer(X_test)
shap.summary_plot(shap_vals, X_test, feature_names=selected_features)

# Calibration Curve
prob_true, prob_pred = calibration_curve(y_test, probs, n_bins=10)
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('Mean Predicted Probability')
plt.ylabel('True Probability')
plt.title('Calibration Curve')
plt.show()

# Time Complexity Profiling
start_time = time.time()
_ = stacking_model.predict(X_test)
end_time = time.time()
print(f"Prediction time: {end_time - start_time:.4f} seconds")

# Bootstrap Test
def bootstrap_test(y_true, y_pred1, y_pred2, n_iter=1000):
    y_true, y_pred1, y_pred2 = np.array(y_true), np.array(y_pred1), np.array(y_pred2)
    diff = np.mean(y_pred1 == y_true) - np.mean(y_pred2 == y_true)
    diffs = []
    for _ in range(n_iter):
        idx = np.random.choice(len(y_true), len(y_true), replace=True)
        d = np.mean(y_pred1[idx] == y_true[idx]) - np.mean(y_pred2[idx] == y_true[idx])
        diffs.append(d)
    p_val = np.mean(np.abs(diffs) >= np.abs(diff))
    return p_val

cat_model = CatBoostClassifier(verbose=0)
cat_model.fit(X_train, y_train)
cat_pred = cat_model.predict(X_test)
p_value = bootstrap_test(y_test, cat_pred, pred)
print(f"Bootstrap Test p-value: {p_value:.4f}")

# McNemar Test
mcnemar_table = confusion_matrix(cat_pred, pred)
mcnemar_result = mcnemar(mcnemar_table, exact=True)
print(f"McNemar's Test p-value: {mcnemar_result.pvalue:.4f}")

# Save best model
joblib.dump(stacking_model, "best_model.pkl")
print("Best model saved as 'best_model.pkl'")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from catboost import CatBoostClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

# Assuming X_train, X_test, y_train, y_test are already defined
# If you're working with Ionosphere dataset:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data"
columns = [f"Feature_{i}" for i in range(1, 35)] + ['status']
data = pd.read_csv(url, header=None, names=columns)
data['status'] = data['status'].map({'g': 1, 'b': 0})
X = data.drop('status', axis=1)
y = data['status']

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Base models for stacking
cat_model = CatBoostClassifier(verbose=0)
stacking_model = StackingClassifier(
    estimators=[('cat', cat_model)],
    final_estimator=LogisticRegression()
)

# Train models
cat_model.fit(X_train, y_train)
stacking_model.fit(X_train, y_train)

# Predict with both models
cat_pred = cat_model.predict(X_test)
stack_pred = stacking_model.predict(X_test)

# Create confusion matrix for the predictions
cm = confusion_matrix(cat_pred, stack_pred)
print(f"Confusion Matrix:\n{cm}")

!pip install --no-cache-dir catboost

!pip install pytorch-tabnet